#!/usr/bin/env python3
"""── the compass, cut into a rose and four letters ───────────────────────

`assets/compass.png` is a compass rose — since 2026-08-28 a star with a
long north spike and no letters, so there is one cut, the rose, and it
turns with the map. (Before that a lettered rose was cut into five, the
letters kept upright; the machinery for more cuts is still here.)
They ship as CSS masks, and for the reason `tools/frame.py` gives, as
data: URIs in a generated file rather than as files: a file:// image
cannot be a mask.

The art is grey on white. White is keyed to nothing, what is left is made
white with its alpha kept, and each cut is halved.

    tools/compass.py          # assets/compass.png → src/compass-art.js

The crops are the art's own: measured once on the sheet, and written
here, so a new sheet is a new set of numbers.
"""
import base64, pathlib, subprocess, sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
SRC = ROOT / 'assets' / 'compass.png'
OUT = ROOT / 'src' / 'compass-art.js'
CUTS = {                     # name: WxH+X+Y on the 225×268 sheet (2026-08-28: the star rose, no letters)
    'rose': '225x268+0+0',
}

def cut(geom):
    return subprocess.run(
        ['magick', str(SRC), '-crop', geom, '+repage', '-fuzz', '18%', '-transparent', 'white',
         '-fill', 'white', '-colorize', '100%', '-resize', '50%',
         '-define', 'png:color-type=4', '-strip', 'PNG:-'],
        check=True, capture_output=True).stdout

def main():
    if not SRC.exists():
        sys.exit(f'no compass at {SRC}')
    parts = {k: base64.b64encode(cut(g)).decode() for k, g in CUTS.items()}
    body = ",\n".join(f"  {k}: 'url(\"data:image/png;base64,{v}\")'" for k, v in parts.items())
    OUT.write_text(
        "'use strict';\n"
        "/* GENERATED by tools/compass.py from assets/compass.png — do not edit.\n"
        "   The compass as CSS masks: the rose, which turns with the map.\n"
        "   Data: URIs because a file:// image cannot be a mask. */\n"
        "const COMPASS_ART = {\n" + body + "\n};\n")
    print(f'wrote {OUT.relative_to(ROOT)}: ' + ', '.join(f'{k} {len(v) * 3 // 4} B' for k, v in parts.items()))

if __name__ == '__main__':
    main()
