#!/usr/bin/env python3
"""── the card frame, baked to a mask the page can use ────────────────────

`assets/card-frame.png` is the bag's floral frame. The page wants it as a
CSS mask — the shape is the PNG's alpha and the ink is the card's own
colour, so the frame wears dim, bone or the inversion exactly as the glyph
does — but Chromium fetches a mask image with CORS, and every file:// URL
is its own opaque origin, so a mask read straight from assets/ resolves to
nothing at all. (The same wall taints a canvas an asset is drawn on.)

So, as with the building sheets, the asset is read once, offline, and what
ships is not the file but the data: `src/frame.js` sets `--frame` on the
root to a data: URI, and the stylesheet masks with the variable. Alpha is
all a mask needs, so the colour is thrown away (everything white, alpha
kept) and the image halved, which is more than the card ever shows.

    tools/frame.py            # assets/card-frame.png → src/frame.js

ImageMagick does the work, as in tools/glyphs.py, for the same reason: it
is on the box and PIL is not.
"""
import base64, pathlib, subprocess, sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
SRC = ROOT / 'assets' / 'card-frame.png'
OUT = ROOT / 'src' / 'frame.js'

def main():
    if not SRC.exists():
        sys.exit(f'no frame at {SRC}')
    png = subprocess.run(
        ['magick', str(SRC), '-resize', '50%', '-fill', 'white', '-colorize', '100%',
         '-define', 'png:color-type=4', '-strip', 'PNG:-'],
        check=True, capture_output=True).stdout
    b64 = base64.b64encode(png).decode()
    OUT.write_text(
        "'use strict';\n"
        "/* GENERATED by tools/frame.py from assets/card-frame.png — do not edit.\n"
        "   The bag's card frame as a CSS mask the page can actually load: a\n"
        "   file:// image cannot be a mask (CORS), a data: URI can. Alpha only,\n"
        "   halved. `--frame` is what index.html masks the cards with. */\n"
        "document.documentElement.style.setProperty('--frame',\n"
        "  'url(\"data:image/png;base64," + b64 + "\")');\n")
    print(f'wrote {OUT.relative_to(ROOT)}: {len(png)} bytes of PNG, {len(b64)} of base64')

if __name__ == '__main__':
    main()
